config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :star_items
  resources :document_versions
  resources :attachments
  resources :calender_events
  resources :todolists
  resources :documents
  resources :messages
  resources :uploads
  resources :attachmentdirs
  resources :calendars
  resources :accesses

  resources :projects do
    resources :todos do
      member do
        post 'finish'
      end

      resources :comments
    end

    member do
      get "members"
      post 'add_member'
      delete 'remove_member'
    end
  end

  resources :users do
    resources :teams
    resources :events
  end

  resources :teams do
    resources :events
    resources :projects

    member do
      get "members"
      post 'add_member'
      delete 'remove_member'
    end
  end

  get '/launchpad' => 'teams#index', as: :launchpad

  root to: 'teams#index'

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  name       :string
#  team_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_projects_on_team_id  (team_id)
#

class Project < ActiveRecord::Base
  belongs_to :team

  has_many :accesses
  has_many :members, through: :accesses, source: :user

  has_many :todos, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :name, presence: true
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :members, :add_member, :remove_member]
  before_action :set_team, only: [:index, :new, :create, :destroy]
  before_action :check_permission, only: [:show]

  def index
    @projects = @team.projects.all
  end

  def show
    @todos = @project.todos.unfinished
  end

  def new
    @project = @team.projects.build
  end

  def create
    @project = @team.projects.build(project_params)
    @project.members << current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to team_projects_path(@team), notice: '创建项目成功' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to team_projects_path(@team), notice: '删除项目成功' }
    end
  end

  def members
    @members = @project.members
  end

  def add_member
    user = User.find(params[:user_id])
    respond_to do |format|
      if !@project.members.include?(user)
        @project.members << user
        format.js { flash[:notice] = '增加成员成功' }
      else
        format.js { flash[:error] = "用户已经增加" }
      end
    end
  end

  def remove_member
    user = User.find(params[:user_id])
    respond_to do |format|
      if @project.members.include?(user)
        @project.members.delete(user)
        format.html { redirect_to members_project_path(@project), notice: '删除成员成功' }
      else
        format.html { redirect_to members_project_path(@project), notice: '成员不存在' }
      end
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def set_team
    @team = Team.find(params[:team_id])
  end

  def project_params
    params[:project].permit(:name)
  end

  def check_permission
    unless @project.members.include?(current_user)
      flash[:error] = "用户没有权限"
      redirect_to request.referer
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= bootstrap_form_for([@team, @project]) do |f| %>
  <%= f.text_field :name, label: "项目名称" %>
  <%= f.submit "创建项目", class: "btn btn-success" %>
<% end %>

app/views/projects/add_member.js.erb
window.location.reload();

app/views/projects/edit.html.erb
<h1>编辑项目</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>所有项目</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to '所有任务', project_path(project), class: "btn btn-default" %>
        <%= link_to '删除', project_path(project, team_id: @team.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '创建项目', new_team_project_path(@team), class: "btn btn-success" %>

<% content_for :script do %>
  <script>window.ProjectsIndexView();</script>
<% end %>

app/views/projects/members.html.erb
<div class="row">
  <div class="col-md-5">
    <h2>项目成员</h2>
  </div>
</div>

<hr/>

<div class="row">
  <div class="col-md-10">
    <% @members.each do |member| %>
      <%= content_tag :span, class: "label label-warning", style: "display: inline-block" do %>
        <%= member.username %>
        <%= link_to remove_member_project_path(@project, user_id: member.id), method: :delete do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      <% end %>
    <% end %>
    <%= select_tag "add-member",
    options_from_collection_for_select(@project.team.members, "id", "username"),
      include_blank: true, class: "add-member", data: { "project-id" => @project.id } %>
  </div>
</div>

<% content_for :script do %>
  <script>window.ProjectsMembersView();</script>
<% end %>

app/views/projects/new.html.erb
<div class="page-header">
  <h2>新建项目</h2>  
</div>

<%= render 'form' %>

<hr/>

<%= link_to '返回', team_projects_path(@team), class: 'btn btn-default' %>

app/views/projects/show.html.erb
<div class="project-header row">
  <div class="project-hd-info col-md-5">
    <h2><%= @project.name %></h2>
  </div>
  <div class="project-links col-md-5 pull-right">
    <h3>
      <%= link_to "#{@project.members.size} 成员", members_project_path(@project), class: "label label-info" %>
    </h3>
  </div>
</div>

<hr/>

<div class="row">
  <div class="col-md-1"><h4>任务</h4></div>
  <div class="col-md-2">
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        添加任务
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a href="#" id="add-todo">添加任务</a></li>
      </ul>
    </div>
  </div>
</div>

<hr/>

<!-- todos list -->
<div class="row">
  <div class="col-md-10">
    <%= content_tag :ul, class: "todos list-group", data: { "project-id" => @project.id } do %>
      <% @todos.each do |todo| %>
        <%= content_tag :li, class: "todo list-group-item", data: { "todo-id" => todo.id  } do %>
          <div class="todo-wrap">
            <label class="checkbox-inline">
              <%= check_box_tag "todo_done" %> <%= link_to todo.name, project_todo_path(@project, todo) %>
            </label>
            <% if todo.assignee || todo.due %>
              <a class="todo-assign-due label label-danger"><%= todo.assignee.try(:username) %> <%= todo.try(:due) %></a>
            <% else %>
              <a class="todo-assign-due label label-info">未指派</a>
            <% end %>
            <span class="hide popover-head">指派任务</span>
            <span class="hide popover-content">
              <%= render "todos/assign_form", project: @project, todo: todo %>
            </span>
            <span class="pull-right">
              <%= link_to "删除", project_todo_path(@project, todo), method: :delete, data: { confirm: "确认删除？" } %>
            </span>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row" id="add-todo-form">
  <div class="col-md-10">
    <%= render "todos/form", project: @project, todo: @project.todos.new %>
  </div>
</div>

<% content_for :script do %>
  <script>window.ProjectsShowView();</script>
<% end %>