config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :star_items
  resources :document_versions
  resources :attachments
  resources :calender_events
  resources :todolists
  resources :documents
  resources :messages
  resources :uploads
  resources :attachmentdirs
  resources :calendars
  resources :accesses

  resources :projects do
    resources :todos do
      member do
        post 'finish'
      end

      resources :comments
    end

    member do
      get "members"
      post 'add_member'
      delete 'remove_member'
    end
  end

  resources :users do
    resources :teams
    resources :events
  end

  resources :teams do
    resources :events
    resources :projects

    member do
      get "members"
      post 'add_member'
      delete 'remove_member'
    end
  end

  get '/launchpad' => 'teams#index', as: :launchpad

  root to: 'teams#index'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Tower', launchpad_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links', team: @team || @project.team %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/user_navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class="nav"><%= link_to '项目', team_projects_path(team) %></li>
<li class="nav"><%= link_to '动态', team_events_path(team) %></li>
<li class="nav"><%= link_to '团队', members_team_path(team) %></li>

app/views/layouts/_user_navigation_links.html.erb
<% if user_signed_in? %>
  <li class="nav"><%= link_to current_user.username, edit_user_registration_path %></li>
  <li class="nav"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
<% else %>
  <li class="nav"><%= link_to "Sign up", new_user_registration_path %></li>
  <li class="nav"><%= link_to "Login", new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tower" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tower" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
      </div>
    </main>
    <footer>
      <%= yield :script %>
    </footer>
  </body>
</html>

app/views/layouts/launchpad.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tower" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tower" %>">
    <%= stylesheet_link_tag 'launchpad', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'launchpad', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header></header>
    <main role="main">
      <div class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
      </div>
    </main>
    <footer>
      <%= yield :script %>
    </footer>
  </body>
</html>